apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-deploy
  name: web-deploy
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30001
  selector:
    app: web-deploy
  type: NodePort